name: Broken Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0-6'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: broken-nightly

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          arguments: :app:assemble

  UnitTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: broken-nightly

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: burrunan/gradle-cache-action@v1
        name: Test
        with:
          arguments: clean testDebug -p ./

  AllUiTests:
    - uses: actions/checkout@v2
      with:
        ref: broken-nightly

    steps:
      - uses: actions/checkout@v2

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Smoke UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          profile: Nexus 6
          script: adb logcat > logs.txt & ./gradlew connectedAndroidTest

      - name: Upload log output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "log_output"
          path: "logs.txt"
          if-no-files-found: ignore

