name: Code review with reusable

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main

jobs:
  Build:
    uses: ./.github/workflows/reusable_build.yml
    secrets: inherit

  UnitTests:
    uses: ./.github/workflows/reusable_unit_tests.yml
    secrets: inherit

  SmokeUiTests:
    uses: ./.github/workflows/reusable_unit_tests.yml
    secrets: inherit
    with:
      android_test_param: "-Pandroid.testInstrumentationRunnerArguments.annotation=com.akjaw.android.next.level.cicd.fruit.SmokeTest"
