name: Code review

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main

jobs:
  Build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false) }}
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          arguments: :app:assemble

  UnitTests:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false) }}
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: burrunan/gradle-cache-action@v1
        name: Test
        with:
          arguments: clean testDebug -p ./

  SmokeUiTests:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false) }}
    runs-on: macos-12

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Smoke UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          profile: Nexus 6
          script: adb logcat > logs.txt & ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=com.akjaw.android.next.level.cicd.fruit.SmokeTest

      - name: Upload log output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "log_output"
          path: "logs.txt"
          if-no-files-found: ignore

