name: Manual distribution

on:
  workflow_dispatch:
    inputs:
      variant:
        description: "Variant (Debug, Release)"
        required: true
        default: "Debug"
      groups:
        description: "Firebase tester groups, should be separated with a comma"
        required: true
        default: "testers"
      description:
        description: "App distribution description"
        required: false
        default: ""

jobs:
  Manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: "Build ${{ github.event.inputs.variant }} for: ${{ github.event.inputs.groups }}"
        run: ./gradlew app:assemble${{ github.event.inputs.variant }}

      - name: Upload apk to Firebase App Distribution
        run: |
          export BUILD_DESCRIPTION="${{ github.event.inputs.description }}"
          export FIREBASE_TESTERS_GROUPS="${{ github.event.inputs.groups }}"
          ./gradlew app:appDistributionUpload${{ github.event.inputs.variant }}