name: Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '00 7 * * 1'

jobs:
  DebugBuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: "Weekly debug build"
        run: ./gradlew app:assembleDebug

      - name: Upload apk to Firebase App Distribution
        run: |
          export BUILD_DESCRIPTION="Weekly Debug build"
          export FIREBASE_TESTERS_GROUPS="testers"
          ./gradlew app:appDistributionUploadDebug
