name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '00 7 * * 1'

jobs:
  DebugBuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Firebase secrets
        uses: ./.github/actions/firebase_secrets
        with:
          GOOGLE_SERVICES_JSON: "${{ secrets.GOOGLE_SERVICES_JSON }}"
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: "Build ${{ github.event.inputs.variant }} for: ${{ github.event.inputs.groups }}"
        run: ./gradlew app:assemble${{ github.event.inputs.variant }}

      - name: Upload apk to Firebase App Distribution
        run: |
          export BUILD_DESCRIPTION="Weekly Debug build"
          export FIREBASE_TESTERS_GROUPS="testers"
          ./gradlew app:appDistributionUploadDebug
